# Default Modulus configuration
defaults:
  - modulus_default
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler:
  decay_rate: 0.95 # reduces learning rate after every multiple of decay steps by this to converge
  decay_steps: 10_000

training:
  rec_results_freq : 100
  max_steps : 1_000 # count of training steps we will use per time frame iteration
  save_network_freq : 1_000 # saving should be done after every time frame -> should equal max steps to save at the end of every timeframe