# Default Modulus configuration
defaults:
  - modulus_default
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler:
  decay_rate: 0.95 # reduces learning rate after every multiple of decay steps by this to converge
  decay_steps: 10_000

training:
  summary_freq : 100
  rec_results_freq : 1_000
  max_steps : 1_000
  save_network_freq : 1_000 
  rec_validation_freq : 10_000